### ISSUE TITLE
fresh install

### ISSUE THREAD

**Issue by gusdrawn** [kleinee/jns#21] opened 2018-04-02 02:40 UTC
I need change the SD in my RPI, but when I try to install this, I get the first time this:

Collecting xlrd==1.1.0
  Downloading xlrd-1.1.0-py2.py3-none-any.whl (108kB)
    100% |████████████████████████████████| 112kB 1.3MB/s 
Installing collected packages: xlrd
Successfully installed xlrd-1.1.0
Collecting XlsxWriter==1.0.2
  Downloading XlsxWriter-1.0.2-py2.py3-none-any.whl (139kB)
    100% |████████████████████████████████| 143kB 1.4MB/s 
Installing collected packages: XlsxWriter
Successfully installed XlsxWriter-1.0.2
Collecting xlwt==1.3.0
  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 1.4MB/s 
Installing collected packages: xlwt
Successfully installed xlwt-1.3.0
Writing default config to: /home/pi/.jupyter/jupyter_notebook_config.py
logname: no login name
Installing IPython kernel spec
Enabling: jupyterlab
- Writing config: /home/pi/.jupyter
    - Validating...
      jupyterlab  OK
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Traceback (most recent call last):
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.venv/jns/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/bqplot/__init__.py", line 60, in <module>
    from .figure import *
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/bqplot/figure.py", line 36, in <module>
    from .scales import Scale, LinearScale
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/bqplot/scales.py", line 44, in <module>
    import numpy as np
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

Enabling IPython clusters tab
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 38002  100 38002    0     0  29503      0  0:00:01  0:00:01 --:--:-- 29503
n-install: ERROR:
  Aborting, because n and/or Node.js-related binaries are already
  in the $PATH:
           
         /usr/bin/node
  
  Please remove any existing n, Node.js installation, then try 
  again.
  

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 julia : Depends: libamd2 (>= 4.5.2) but it is not installable
         Depends: libcamd2 (>= 4.5.2) but it is not installable
         Depends: libcholmod3 (>= 4.5.2) but it is not installable
         Depends: libspqr2 but it is not installable
         Depends: libumfpack5 (>= 4.5.2) but it is not installable
         Depends: libpcre2-dev but it is not installable
         Depends: libdsfmt-dev but it is not installable
         Depends: libopenblas-dev but it is not installable
         Depends: libfftw3-dev but it is not installable
         Depends: libgmp-dev but it is not installable
         Depends: libmpfr-dev but it is not installable
         Depends: libarpack2-dev but it is not installable
         Depends: libsuitesparse-dev but it is not installable
         Depends: libopenspecfun-dev but it is not installable
         Depends: libcurl4-openssl-dev but it is not installable
         Depends: patchelf but it is not installable
E: Unable to correct problems, you have held broken packages.
bash: line 2: julia: command not found
bash: line 3: julia: command not found

**Comment by m-r-white** [comment] 2018-04-04 14:34
Thank you for this, now I don't have to keep installing Jupyter on all new pi's. I've just received the same errors as @gusdrawn though.

My environment:
raspberry pi 3b
(2018-3-13) Raspbian Stretch - NOTE: **Not** Stretch Lite

My steps:
ran SD Card Formatter on stick
etcher .img to sd card
**this did not work**: sudo apt ./inst_jns.sh
this worked: sudo ./inst_jns.sh

Error: (tail)
Successfully installed xlrd-1.1.0
Collecting XlsxWriter==1.0.2
  Downloading XlsxWriter-1.0.2-py2.py3-none-any.whl (139kB)
    100% |████████████████████████████████| 143kB 1.3MB/s 
Installing collected packages: XlsxWriter
Successfully installed XlsxWriter-1.0.2
Collecting xlwt==1.3.0
  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 1.2MB/s 
Installing collected packages: xlwt
Successfully installed xlwt-1.3.0
Writing default config to: /home/pi/.jupyter/jupyter_notebook_config.py
Installing IPython kernel spec
Enabling: jupyterlab
- Writing config: /home/pi/.jupyter
    - Validating...
      jupyterlab  OK
Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK
Traceback (most recent call last):
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/.venv/jns/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 896, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 872, in toggle_nbextension_python
    logger=self.log)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 483, in enable_nbextension_python
    logger=logger)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/bqplot/__init__.py", line 60, in <module>
    from .figure import *
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/bqplot/figure.py", line 36, in <module>
    from .scales import Scale, LinearScale
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/bqplot/scales.py", line 44, in <module>
    import numpy as np
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/home/pi/.venv/jns/lib/python3.5/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory

Enabling IPython clusters tab
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 38002  100 38002    0     0  77680      0 --:--:-- --:--:-- --:--:-- 77680
n-install: ERROR:
  Aborting, because n and/or Node.js-related binaries are already
  in the $PATH:
           
         /usr/bin/node
  
  Please remove any existing n, Node.js installation, then try 
  again.
  

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 julia : Depends: libamd2 (>= 4.5.2) but it is not installable
         Depends: libcamd2 (>= 4.5.2) but it is not installable
         Depends: libcholmod3 (>= 4.5.2) but it is not installable
         Depends: libspqr2 but it is not installable
         Depends: libumfpack5 (>= 4.5.2) but it is not installable
         Depends: libpcre2-dev but it is not installable
         Depends: libdsfmt-dev but it is not installable
         Depends: libopenblas-dev but it is not installable
         Depends: libfftw3-dev but it is not installable
         Depends: libgmp-dev but it is not installable
         Depends: libmpfr-dev but it is not installable
         Depends: libarpack2-dev but it is not installable
         Depends: libsuitesparse-dev but it is not installable
         Depends: libopenspecfun-dev but it is not installable
         Depends: libcurl4-openssl-dev but it is not installable
         Depends: patchelf but it is not installable
E: Unable to correct problems, you have held broken packages.
bash: line 2: julia: command not found
bash: line 3: julia: command not found


TYPO in your README I just noticed, "Installation", "First boot with fresh SD card" "cd~/jns" second bullet. "Upon saving te..."

**Comment by kleinee** [comment] 2018-04-05 05:05
Did anyone try a fresh install on Raspbian Stretch Lite as intended and encountered the same issues?

**Comment by gusdrawn** [comment] 2018-04-06 12:42
Let me try that, today. @m-r-white

**Comment by kleinee** [comment] 2018-04-07 17:09
@gusdrawn @m-r-white: I ran a fresh install using the Raspbian Stretch Desktop image as a starting point. At the core the issue that both of you reported is that the starting point of the installations have a 'nodejs' < version 5 installed. 

* For `conf_jupyter.sh` to  run through `nodjs` needs to be updated prior to executing the scripts. I added a section to to the `README.md` and modified 'inst_jupyter.sh' to skip the installation of `nodjs` if it is already present putting it in the user's responsibility to upgrade `nodejs`/ This is better than compromising existing installations. Even after 'conf_jypyter.sh' failed due to 'nodejs' being too old, it is fine to upgrade 'nodejs' and then run 'conf_jupyter.sh' again.

* I also noticed that `logname` is undefined in the Desktop version. In your installations please check `/home/pi/.jupyter/jupyter_notebook_config.py` and verify that the line `c.NotebookApp.notebook_dir = '/home/pi/notebooks' is correct. For future users I removed `logname` from the script and hard-coded the username as `pi`. 

If you want use the server on the Pi's  desktop, you might want to open the browser whenever the server is started. Change  'c.NotebookApp.open_browser = False' to 'c.NotebookApp.open_browser = True`.

Have fun!

Eckhard

**Comment by kleinee** [comment] 2018-04-08 14:37
@gusdrawn @m-r-white: Is it ok for me to close this issue? At my end Jupyter is running fine on the Desktop version of Raspbian Stretch. Thanks for your feedback.

Eckhard

**Comment by m-r-white** [comment] 2018-04-08 16:52
Yes, thank you again!

**Closed** 2018-04-09 02:02 UTC
